name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build (standard)
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 17
      - name: Build With Version
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && steps.semantic.outputs.new_release_published == 'true'
        run: dotnet build -p:Version=${{ steps.semantic.outputs.new_release_version }} --configuration Release --no-restore
      - name: Pack
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && steps.dryrun.outputs.new_release_published == 'true'
        run: dotnet pack -p:Version=${{ steps.semantic.outputs.new_release_version }} -p:PackageReleaseNotes="${{ steps.semantic.outputs.new_release_notes }}" --no-build --configuration Release DevDistricts/DevDistricts.csproj --output .
      - name: Nuget Push
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && steps.semantic.outputs.new_release_published == 'true'
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLISH_TO_NUGET_ORG }} --skip-duplicate
        